// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQZ_nwlwhqBspVH9UqTFIPfEj2gM-hiS0',
    appId: '1:519615294236:web:1c13c577ba4f308beb28d9',
    messagingSenderId: '519615294236',
    projectId: 'pasanaq-sol',
    authDomain: 'pasanaq-sol.firebaseapp.com',
    storageBucket: 'pasanaq-sol.appspot.com',
    measurementId: 'G-2MR951DFY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIMxoQ1c928TD3JF03ONzy-HQeX4gChrQ',
    appId: '1:519615294236:android:04130df81935f178eb28d9',
    messagingSenderId: '519615294236',
    projectId: 'pasanaq-sol',
    storageBucket: 'pasanaq-sol.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOiON91XgPxQ1YMrpEZRRNcAh3pbIiKCY',
    appId: '1:519615294236:ios:1bea114e335255d1eb28d9',
    messagingSenderId: '519615294236',
    projectId: 'pasanaq-sol',
    storageBucket: 'pasanaq-sol.appspot.com',
    iosClientId: '519615294236-mi6amcpruf979hfc0002tahtbpcp7ti9.apps.googleusercontent.com',
    iosBundleId: 'com.pasanaq.sol',
  );
}
